import { brandCoreZhCN } from '@/content/brand-core.zh-CN';

export type HomeSeoLocale = 'en' | 'cn' | 'ko' | 'es';

export const HOME_CANONICAL_PATH = '/';

export const homeSeoLocaleCopy = {
  en: {
    path: '/',
    title: 'AI Stock Analysis & Stock Research App | ZISO AI',
    description:
      'ZISO AI is an AI stock analysis and stock research app for serious retail investors. Review markets after the close, audit reasoning, and prepare the next session.',
    keywords: [
      'AI stock analysis',
      'stock research',
      'AI stock research',
      'stock analysis app',
      'stock market analysis',
      'post-close market research',
      'stock research app',
      'AI stock research app',
      'AI stock analysis app',
      'stock market research app',
      'stock market research tool',
      'AI investing assistant',
      'stock prediction research',
      'stock analysis tool',
      'AI stock analysis tool',
      'AI stock research tool',
      'AI stock market analysis',
      'AI equity research',
      'equity research tool',
      'investment research assistant',
      'retail investor research tool',
      'retail investor tools',
      'self directed investor tools',
      'stock research for retail investors',
      'stock analysis for retail investors',
      'post market stock analysis',
      'after hours stock research',
      'market close stock research',
      'daily stock research',
      'daily market briefing',
      'stock market briefing app',
      'AI market briefing',
      'watchlist analysis',
      'stock watchlist app',
      'best stock watchlist app',
      'stock watchlist alerts',
      'stock alerts app',
      'best app for stock alerts',
      'stock risk analysis',
      'stock risk management',
      'stock risk assessment',
      'trading discipline',
      'trade planning app',
      'next session trading plan',
      'stock decision support',
      'investment decision support',
      'explainable AI stock analysis',
      'AI stock reasoning',
      'AI stock reports',
      'stock analysis reports',
      'technical stock analysis app',
      'fundamental stock analysis tool',
      'market sentiment analysis stocks',
      'US stock analysis',
      'Hong Kong stock analysis',
      'China A-share analysis',
      'global stock research',
      'ZISO AI',
    ],
  },
  cn: {
    path: '/cn',
    title: 'AI 股票分析与盘后复盘工具 | 知守 AI',
    description:
      '知守 AI 是面向严肃投资者的 AI 股票分析与盘后复盘工具，帮助用户审计市场逻辑、设置风险边界，并为下一交易日制定计划。',
    keywords: [
      'AI 股票分析',
      '股票分析工具',
      '盘后复盘',
      'AI 投研助手',
      '股票研究工具',
      'AI 股票研究',
      'AI 股票研究工具',
      'AI 投资助手',
      'AI 投资研究',
      '股票投研助手',
      '股票投研工具',
      '盘后股票分析',
      '盘后市场复盘',
      '每日市场简报',
      '股票市场简报',
      '自选股分析',
      '自选股提醒',
      '股票预警工具',
      '股票风险分析',
      '股票风险管理',
      '交易计划工具',
      '交易纪律',
      '投资决策辅助',
      '可解释 AI 股票分析',
      '美股分析',
      '港股分析',
      'A股分析',
      '全球股票研究',
      '知守 AI',
      'ZISO AI',
    ],
  },
  ko: {
    path: '/ko',
    title: 'AI 주식 분석 및 리서치 앱 | ZISO AI',
    description:
      'ZISO AI는 진지한 개인 투자자를 위한 AI 주식 분석 및 장 마감 후 리서치 앱입니다. 시장을 복기하고 추론을 감사하며 다음 세션을 준비합니다.',
    keywords: [
      'AI stock analysis',
      'stock research',
      'AI 주식 분석',
      '주식 리서치 앱',
      '주식 분석 앱',
      '장 마감 리서치',
      '투자 리서치 도구',
      'AI 투자 리서치',
      '주식 시장 분석',
      '주식 리서치 도구',
      '개인 투자자 리서치',
      '관심종목 분석',
      '시장 마감 후 분석',
      '리스크 관리',
      '매매 계획',
      'ZISO AI',
    ],
  },
  es: {
    path: '/es',
    title: 'Análisis de Acciones con IA | ZISO AI',
    description:
      'ZISO AI es una app de análisis de acciones con IA para inversores serios. Revisa el mercado tras el cierre, audita el razonamiento y prepara la próxima sesión.',
    keywords: [
      'AI stock analysis',
      'stock research',
      'analisis de acciones con IA',
      'analisis bursatil con IA',
      'app de analisis de acciones',
      'investigacion de mercado post-cierre',
      'herramienta de investigacion bursatil',
      'app de investigacion bursatil',
      'asistente de inversion con IA',
      'analisis de mercado con IA',
      'analisis de acciones para inversores minoristas',
      'investigacion de acciones',
      'analisis de riesgo bursatil',
      'gestion de riesgo trading',
      'alertas de acciones',
      'lista de seguimiento de acciones',
      'ZISO AI',
    ],
  },
} as const;

export const homeSeoKeywords = Array.from(
  new Set(Object.values(homeSeoLocaleCopy).flatMap((copy) => copy.keywords)),
);

export function buildHomeSoftwareJsonLd(locale: HomeSeoLocale = 'en'): Record<string, unknown> {
  const copy = homeSeoLocaleCopy[locale];
  const origin = brandCoreZhCN.domain.replace(/\/$/, '');
  const localeMap: Record<HomeSeoLocale, string> = {
    en: 'en-US',
    cn: 'zh-CN',
    ko: 'ko-KR',
    es: 'es-ES',
  };

  return {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'ZISO AI',
    alternateName: [
      'ZISO AI stock analysis app',
      'ZISO stock research app',
      '知守 AI',
      homeSeoLocaleCopy.ko.title,
      homeSeoLocaleCopy.es.title,
    ],
    applicationCategory: 'FinanceApplication',
    applicationSubCategory: 'AI stock analysis and stock research',
    operatingSystem: 'Web',
    url: `${origin}${copy.path}`,
    inLanguage: localeMap[locale],
    description: copy.description,
    keywords: copy.keywords.join(', '),
    featureList: [
      'AI stock analysis for US, Hong Kong, and China A-share markets',
      'Post-close market review and next-session preparation',
      'Multi-agent rationale audit and logic trace',
      'Risk boundaries, tactical anchors, and watchlist alerts',
    ],
    audience: {
      '@type': 'Audience',
      audienceType: 'Serious retail investors',
    },
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
    },
  };
}
